

service: my-express-api
app: my-aws-node-express-api-app
org: kevinguitars
plugins:
  - serverless-offline
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::"

functions:
  functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      
  listAllFuncionarios:
    handler: index.handler
    events:
      - http: 'GET /funcionario/list'

  insertFuncionario:
    handler: index.handler
    events:
      - http: 'POST /funcionario'

  deleteFuncionario:
    handler: index.handler
    events:
      - http: 'DELETE /funcionario/{proxy+}'

  updateFuncionario:
    handler: index.handler
    events:
      - http: 'PUT /funcionario/{proxy+}'


